[project]
name = "pipe_lens"
version = "1.0.0"
dependencies = [
    "numpy==2.0.0",
    "matplotlib==3.10.0",
    "scipy==1.14.1",
    "mini-auspex==1.5.11",
    "tqdm==4.67.1"
]

[tool.setuptools.packages]
find = { where = ["."], include = ["pipe_lens"], exclude = ["tables", "figures"] }